[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "daily_digest"
version = "0.1.0"
dependencies = [
    "requests"
]

[tool.setuptools.packages.find]
where = ["src"]